all:
  hosts:
    node-1:
      ansible_host: 192.168.0.11
      ip: 192.168.0.11
      access_ip: 192.168.0.11
      ansible_user: ubuntu
    node-2:
      ansible_host: 192.168.0.16
      ip: 192.168.0.16
      access_ip: 192.168.0.16
      ansible_user: ubuntu
    node-3:
      ansible_host: 192.168.0.10
      ip: 192.168.0.10
      access_ip: 192.168.0.10
      ansible_user: ubuntu
    node-4:
      ansible_host: 192.168.0.7
      ip: 192.168.0.7
      access_ip: 192.168.0.7
      ansible_user: ubuntu
    node-5:
      ansible_host: 192.168.0.8
      ip: 192.168.0.8
      access_ip: 192.168.0.8
      ansible_user: ubuntu
    bastion:
      ansible_host: 208.113.129.70
      ansible_user: ubuntu
  children:
    bastion:
      hosts:
        bastion:
    kube_control_plane:
      hosts:
        node-1:
        node-2:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
        node-4:
        node-5:
    etcd:
      hosts:
        node-1:
        node-2:
        node-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
